development:
  insurance_api: http://localhost:3000/api/v1
  comparator_api: http://localhost:4000/api/v1
  payment_api: http://localhost:5000/api/v1


test:
  insurance_api: http://localhost:3000/api/v1
  comparator_api: http://localhost:4000/api/v1
  payment_api: http://localhost:5000/api/v1


production:
  insurance_api: http://localhost:3000/api/v1
  comparator_api: http://localhost:4000/api/v1
  payment_api: http://localhost:5000/api/v1
